%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.1.1

-ifndef(test).
-define(test, true).

-define(test_gpb_version, "4.1.1").

-ifndef('MSG2_PB_H').
-define('MSG2_PB_H', true).
-record(msg2,
        {list = []              :: [non_neg_integer()] | undefined, % = 1, 32 bits
         int                    :: non_neg_integer(), % = 2, 32 bits
         opt                    :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('MSG5_PB_H').
-define('MSG5_PB_H', true).
-record(msg5,
        {list = []              :: [non_neg_integer()] | undefined, % = 1, 32 bits
         int                    :: non_neg_integer(), % = 2, 32 bits
         opt                    :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('MSG4_PB_H').
-define('MSG4_PB_H', true).
-record(msg4,
        {list = []              :: [non_neg_integer()] | undefined, % = 1, 32 bits
         int                    :: non_neg_integer(), % = 2, 32 bits
         opt                    :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('MSG1_PB_H').
-define('MSG1_PB_H', true).
-record(msg1,
        {list = []              :: [non_neg_integer()] | undefined, % = 1, 32 bits
         int                    :: non_neg_integer(), % = 2, 32 bits
         opt                    :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('MSG_PB_H').
-define('MSG_PB_H', true).
-record(msg,
        {list = []              :: [non_neg_integer()] | undefined, % = 1, 32 bits
         int                    :: non_neg_integer(), % = 2, 32 bits
         opt                    :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-ifndef('MSG3_PB_H').
-define('MSG3_PB_H', true).
-record(msg3,
        {list = []              :: [non_neg_integer()] | undefined, % = 1, 32 bits
         int                    :: non_neg_integer(), % = 2, 32 bits
         opt                    :: non_neg_integer() | undefined % = 3, 32 bits
        }).
-endif.

-endif.
